const CurrentAppointmentsAssignEval = require ('../../../Locators/Admin/Current_AppointmentDetails.json')

export class CurrentAppointmentAssignEvaluations{
    AdminSelection(){
        cy.xpath(CurrentAppointmentsAssignEval.Current_AppointmentDetailsLocators.AdminSelection).click()
        cy.wait(4000)     
    }
    Select_Appointments(){
        cy.xpath(CurrentAppointmentsAssignEval.Current_AppointmentDetailsLocators.Select_Appointments).click()
        cy.wait(4000)     
    }
    Current_Appointments(){
        cy.xpath(CurrentAppointmentsAssignEval.Current_AppointmentDetailsLocators.Current_Appointments).click()
        cy.wait(4000)     
    }
    Search_Provider1(pName1){
        cy.xpath(CurrentAppointmentsAssignEval.Current_AppointmentDetailsLocators.Search_Provider_Member).type(pName1)
        cy.wait(4000)     
    }
    Search_Provider2(pName2){
        cy.xpath(CurrentAppointmentsAssignEval.Current_AppointmentDetailsLocators.Search_Provider_Member).type(pName2)
        cy.wait(4000)     
    }
    Search_Member(mName){
        cy.xpath(CurrentAppointmentsAssignEval.Current_AppointmentDetailsLocators.Search_Provider_Member).type(mName)
        cy.wait(4000)     
    }
    Open_Appointment(){
        cy.xpath(CurrentAppointmentsAssignEval.Current_AppointmentDetailsLocators.Open_Appointment).click()
        cy.wait(4000)     
    }
    Assign_Evaluations(){
        cy.xpath(CurrentAppointmentsAssignEval.Current_AppointmentDetailsLocators.Assign_Evaluations).click()
        cy.wait(4000)     
    }
    searchEvaluation1(evalName1){
        cy.xpath(CurrentAppointmentsAssignEval.Current_AppointmentDetailsLocators.searchEvaluations).type(evalName1)
        cy.wait(4000)     
    }
    searchEvaluation2(evalName2){
        cy.xpath(CurrentAppointmentsAssignEval.Current_AppointmentDetailsLocators.searchEvaluations).type(evalName2)
        cy.wait(4000)     
    }
    searchEvaluation3(evalName3){
        cy.xpath(CurrentAppointmentsAssignEval.Current_AppointmentDetailsLocators.searchEvaluations).type(evalName3)
        cy.wait(4000)     
    }
    Evaluation1(){
        cy.xpath(CurrentAppointmentsAssignEval.Current_AppointmentDetailsLocators.Evaluation1).click()
        cy.wait(4000)     
    }
    Evaluation2(){
        cy.xpath(CurrentAppointmentsAssignEval.Current_AppointmentDetailsLocators.Evaluation2).click()
        cy.wait(4000)     
    }
    Evaluation3(){
        cy.xpath(CurrentAppointmentsAssignEval.Current_AppointmentDetailsLocators.Evaluation3).click()
        cy.wait(4000)     
    }
    AddSelected_btn(){
        cy.xpath(CurrentAppointmentsAssignEval.Current_AppointmentDetailsLocators.AddSelected_btn).click()
        cy.wait(4000)     
    }
    CancelEvaluation(){
        cy.xpath(CurrentAppointmentsAssignEval.Current_AppointmentDetailsLocators.CancelEvaluation).click()
        cy.wait(4000)     
    }
    MessageProvider(){
        cy.xpath(CurrentAppointmentsAssignEval.Current_AppointmentDetailsLocators.MessageProvider).click()
        cy.wait(4000)     
    }
    
}